server:
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: com.mongodb.Mongo
  data:
    mongodb:
      database: ${mongodb_database:ex-rest}
      host: ${mongodb_ip:localhost}
      port: ${mongodb_port:27017}
logging:
  level:
    ROOT: DEBUG
debug: true
